### ISSUE TITLE
Can the extension persists the PMAK so that I don't have to find it everytime I want to run a collection?

### ISSUE THREAD

**Issue by benja-M-1** [loopDelicious/docker-extension#4]
When the extension starts, the first thing to do is to provide the PKAM. The thing is, it is only visible when it is generated. So I somehow have to save it somewhere or recreate a new one everytime I want to use the extension. I wish I can enter the key once and the extension remembers it. If I need to change it then I'd click to a button to reconfigure it.

@loopDelicious WDYT? I think it is feasible with local storage. I am going to give it a try :)

**Comment by benja-M-1** [comment]
So it is not recommended to use local storage as the values will be available to any other extensions... I will try to think about another solution

**Comment by loopDelicious** [comment]
yes yes - i noted a TODO to keep in local storage! otherwise need to auth through Postman @benja-M-1

**Comment by benja-M-1** [comment]
Is there a doc for authenticating through postman? That would be the best option imo :)

**Comment by loopDelicious** [comment]
> Save the API key either in the volume created by the extension, or using local storage directly from the javascript code of the app.

**Comment by loopDelicious** [comment]
@itsCheithanya it's all yours!

**Comment by lucbpz** [comment]
Hi @loopDelicious! @benja-M-1 and all of our team talked about how we can include a mechanism to store keys. In the meantime, we wanted to contribute with #12 that we hope it helps your users!
