### ISSUE TITLE
Update icon for light and dark mode

### ISSUE THREAD

**Issue by loopDelicious** [loopDelicious/docker-extension#5]
> In order to comply to accessibility standards it is recommended to use the colors mentioned in the Docker color palette for both light and dark mode

Update the extension icon in the sidebar to accommodate light and dark modes.
https://voyager.postman.com/icon/newman-helmet-icon-dark-postman.svg
https://voyager.postman.com/icon/newman-helmet-icon-light-postman.svg

**Comment by krshkodes** [comment]
I would like to work on this

**Comment by loopDelicious** [comment]
You got this one @krshkodes 👍

**Comment by krshkodes** [comment]
@loopDelicious I am unable to find the file of the sidebar component, can you please assist me?

**Comment by loopDelicious** [comment]
I added the icon link to the root directory level `Dockerfile`. I'm not sure how to implement light and dark mode icon. Can you do some research to see how other extensions have managed this? Or look in the docs perhaps?

**Comment by benja-M-1** [comment]
Hi 👋  here is the default icon that is used when one generates an extension. Its colour changes depending on the theme of Docker Desktop. 
Maybe you can find something that will help you here :) 

![docker](https://user-images.githubusercontent.com/212269/193771599-a91ba8a5-b8d2-4da1-b102-4a7fc15a2405.svg)

**Comment by krshkun** [comment]
The docker docs - ask to use a icon that is good for both themes, but not mention anything about different icons in light and dark mode

https://docs.docker.com/desktop/extensions-sdk/design/design-guidelines/

**Comment by benja-M-1** [comment]
Indeed, it must be the same icon.

**Comment by kaggrwal** [comment]
Hi @benja-M-1 ,and @loopDelicious ,

I have redesigned the logo so that it can work for both light and dark mode. I have tested it in my local system, it is working fine, Please review and merge it. Let me know if it requires any improvement.
Apology, i did the issue without getting it assigned to me first. Thanks for providing me opportunity to contribute to docker community :)
