### ISSUE TITLE
Image not build for linux/arm64

### ISSUE THREAD

**Issue by ipedrazas** [loopDelicious/docker-extension#8]
The extension is trying to run the image `joycelin79/htmlreporter-with-template:latest` that is only built for `amd64` https://hub.docker.com/r/joycelin79/htmlreporter-with-template/tags

<img width="1315" alt="Screenshot 2022-10-10 at 11 15 27" src="https://user-images.githubusercontent.com/32796/194844309-35730f6a-1515-4efe-a6f2-bfcc8a85bd69.png">

The extension throws the following error when running in a non-intel Mac:

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

The quick fix is to build `joycelin79/htmlreporter-with-template` for multi-architectures:

`docker buildx build --platform linux/arm64,linux/amd64 -t joycelin79/htmlreporter-with-template:latest . --push`

If you're using Github actions to build the image, I can provide you the steps to do the same.

The not-so-quick fix is to use that image as the extension's VM. This will allow you to do things like this: 

```
let newmanURL = "https://api.getpostman.com/collections/" + collectionID +"?apikey=" + apiKey;
await ddClient.extension.host.cli.exec("newman", ["run", "newmanURL", "..."], {
  stream: {
    onOutput(data: { stdout: string } | { stderr: string }): void {
      if (data.stdout) {
        console.error(data.stdout);
      } else {
        console.log(data.stderr);
      }
    },
    onError(error: any): void {
      console.error(error);
    },
    onClose(exitCode: number): void {
      console.log("onClose with exit code " + exitCode);
    },
  },
});
```
I understand this change requires more time and knowledge, but I just wanted to point the way :)

https://docs.docker.com/desktop/extensions-sdk/dev/api/backend/#invoke-an-extension-binary-on-the-host

**Comment by loopDelicious** [comment]
Thanks @ipedrazas - I did that for the root docker image, but not this one. Pushed!
