### ISSUE TITLE
Update displayed results to follow style guide

### ISSUE THREAD

**Issue by loopDelicious** [loopDelicious/docker-extension#9]
The collection run results are displayed in an HTML template (see `file.hbs`). Update the theme (e.g. color palette) to follow the Docker MUI style guide: https://docs.docker.com/desktop/extensions-sdk/design/overview/.

**Comment by AniqJaved** [comment]
@loopDelicious can I work on this issue?

**Comment by loopDelicious** [comment]
@AniqJaved it's all yours!

**Comment by AniqJaved** [comment]
Working on it🏓
